# Generated by Django 3.1.3 on 2021-09-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210910_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_card_last4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent_id',
        ),
    ]
